sudo: required
notifications:
  email: false

language: python
services:
  - docker

branches:
  only:
    - gh_12_ci

before_install:
  - pip install -U pip
  - docker pull dkarchmervue/python34-opencv3
install:
  - pip install --pre -r requirements.txt

python:
  - "3.4"
script:
  - py.test
