sudo: false
language: python

branches:
  only:
    - gh_12_ci

before_install:
 - sudo apt-get update
 - sudo apt-get install python-opencv
 - sudo dpkg -L python-opencv
install:
  - "pip install --pre -r requirements.txt"

python:
  - "3.4"
script:
  - py.test
