sudo: false
notifications:
  email: false
  webhooks:
    - https://smsapi.free-mobile.fr/sendmsg?user=10194111&pass=GC2q9I0YpfpbfK&msg=tabt+build%3$WEB_TESTRESULTS

language: python
python:
  - "3.4"
cache:
  pip
addons:
  apt:
    packages:
    - build-essential
    - cmake
    - git
    - pkg-config
    - libjpeg8-dev
    - libtiff4-dev
    - libjasper-dev
    - libpng12-dev
    - libatlas-base-dev
    - gfortran

branches:
  only:
    - gh_12_ci

before_install:
  - echo $PWD
  - pip install -U pip
  - pip install coveralls
install:
  - pip install --pre -r requirements.txt
  - bash install_opencv.sh
script:
  - coverage run -m py.test | tee -a testresults
  - TESTRESULTS=`cat testresults | tail -n 1`
  - WEB_TESTRESULTS=${TESTRESULTS//=/}
  - WEB_TESTRESULTS=${WEB_TESTRESULTS// /+}
after_success:
  - coveralls
