sudo: false
notifications:
  email: false

language: python
python:
  - "3.4"
cache:
  pip
addons:
  apt:
    packages:
    - build-essential
    - cmake
    - git
    - pkg-config
    - libjpeg8-dev
    - libtiff4-dev
    - libjasper-dev
    - libpng12-dev
    - libatlas-base-dev
    - gfortran

branches:
  only:
    - master
    - develop
    - gh_12_ci

before_install:
  - pip install -U pip
  - pip install coveralls
install:
  - pip install --pre -r requirements.txt
  - bash install_opencv.sh
script:
  - coverage run -m py.test > testresults

after_script:
  - cat testresults
  - bash notify_tests_passed.sh
after_success:
  - coveralls
