sudo: false
notifications:
  email: false
  webhooks:
    - https://smsapi.free-mobile.fr/sendmsg?user=10194111&pass=GC2q9I0YpfpbfK&msg=tabt+build+finished

language: python
python:
  - "3.4"

addons:
  apt:
    packages:
    - build-essential
    - cmake
    - git
    - pkg-config
    - libjpeg8-dev
    - libtiff4-dev
    - libjasper-dev
    - libpng12-dev
    - libatlas-base-dev
    - gfortran
    - python3.4-dev

branches:
  only:
    - gh_12_ci

before_install:
  - ls -al /opt/python/3.4.2/lib/
  - pip install -U pip
install:
  - pip install --pre -r requirements.txt
  - bash install_opencv.sh
  - ls -R opencv3.0/lib
script:
  - coverage run -m py.test
after_success:
  - coveralls
